### ISSUE TITLE
Error: release activiti failed

### ISSUE THREAD

**Issue by unibravoc** [Activiti/activiti-cloud-full-chart#567]
Helm charts installation problem.

Helm 3
Docker 3
MacOS Mojave 14

**Error: release activiti failed, and has been uninstalled due to atomic being set: timed out waiting for the condition**

**after try:**
Error: query: failed to query with labels: rpc error: code = Unavailable desc = transport is closing

**after try:**
helm UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress

**Comment by mteodori** [comment]
please provide more information, like values you're passing etc

**Comment by mteodori** [comment]
closing this as helm deployment is tested on Travis in Activiti/activiti-cloud-application
